# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flightplan < Formula
  desc "Local-first issue tracker for AI agent workflows"
  homepage "https://github.com/turn-radius/flightplan"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/turn-radius/flightplan/releases/download/v0.2.1/flightplan_darwin_amd64.tar.gz"
      sha256 "20e931181a44441c5afcd5640ff4bc7187cb445911a1bee59726220ced67801b"

      define_method(:install) do
        bin.install "fp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/turn-radius/flightplan/releases/download/v0.2.1/flightplan_darwin_arm64.tar.gz"
      sha256 "ae4be8845a4e0eec98ab2996e7ee996030e5df0f677d6c03a2f335a5e82366d2"

      define_method(:install) do
        bin.install "fp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/turn-radius/flightplan/releases/download/v0.2.1/flightplan_linux_amd64.tar.gz"
      sha256 "30732ef5f015a2f6ee16fbd36ffe17596d4c709dcdadbb3907de49be3052df3a"
      define_method(:install) do
        bin.install "fp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turn-radius/flightplan/releases/download/v0.2.1/flightplan_linux_arm64.tar.gz"
      sha256 "cac53debc9e887df5e260197a45353da45115a7a3a16dc0d734273969ce60530"
      define_method(:install) do
        bin.install "fp"
      end
    end
  end

  test do
    system "#{bin}/fp", "--help"
  end
end
