# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flightplan < Formula
  desc "Local-first issue tracker for AI agent workflows"
  homepage "https://github.com/turn-radius/flightplan"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/turn-radius/flightplan/releases/download/v0.2.0/flightplan_darwin_amd64.tar.gz"
      sha256 "bf2196cd705716260530f0128696af2369377998251086b105d1f990c752de80"

      define_method(:install) do
        bin.install "fp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/turn-radius/flightplan/releases/download/v0.2.0/flightplan_darwin_arm64.tar.gz"
      sha256 "68b641463741d3b1175b03af8c4b9f7d3cc653f3369cdb26d766b9f076b1e562"

      define_method(:install) do
        bin.install "fp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/turn-radius/flightplan/releases/download/v0.2.0/flightplan_linux_amd64.tar.gz"
      sha256 "6a3bbcee58836fe09f950ee12aeed72ead5c4ec4cbeae1b40443fc553b5f3b22"
      define_method(:install) do
        bin.install "fp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turn-radius/flightplan/releases/download/v0.2.0/flightplan_linux_arm64.tar.gz"
      sha256 "837054f722151cf0d68889c7bd32dc2f5cde0a9d7236bfafbcf232f7e06affeb"
      define_method(:install) do
        bin.install "fp"
      end
    end
  end

  test do
    system "#{bin}/fp", "--help"
  end
end
